### ISSUE TITLE
Profiler: An additional PriorityScheduler stack is not being identified as idle

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#271]
This stack was not being auto detected as being idle, even though idle stack 1 and 2 was present in the sample also.
```
   at java.base@10.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   at java.base@10.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:323)
   at org.threadly.concurrent.PriorityScheduler$WorkerPool.workerIdle(PriorityScheduler.java:819)
   at org.threadly.concurrent.PriorityScheduler$Worker.run(PriorityScheduler.java:952)
   at java.base@10.0.2/java.lang.Thread.run(Thread.java:844)
```

**Comment by jentfoo** [comment]
This third stack is a stack witnessed when the scheduler is attempting to avoid starting an additional thread.  This is a much harder stack to capture, so marking as wont fix unless someone feels this is a significant annoyance.
